In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import OneHotEncoder

In [27]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/mushroom-classification")

print("Path to dataset files:", path)

name = "mushrooms.csv"
file_path = os.path.join(path,name)
print(file_path)
df = pd.read_csv(file_path)

Path to dataset files: /home/samuele/.cache/kagglehub/datasets/uciml/mushroom-classification/versions/1
/home/samuele/.cache/kagglehub/datasets/uciml/mushroom-classification/versions/1/mushrooms.csv

In [28]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [29]:
feature_cols = df.columns[1:]
feature_cols

target_col = ["class"]
target_col

['class']

In [30]:
#prendo X per le features e Y per il target

X = df[feature_cols]
X

Y = df[target_col]
Y

     class
0        p
1        e
2        e
3        p
4        e
...    ...
8119     e
8120     e
8121     e
8122     p
8123     e

[8124 rows x 1 columns]

In [33]:
encoder = OneHotEncoder(sparse_output = False)

encoded_data = encoder.fit_transform(df[feature_cols])

X = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(feature_cols))

X

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8120,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8121,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8122,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8123,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [35]:
encoded_data = encoder.fit_transform(df[target_col])

Y = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(target_col))

Y

      class_e  class_p
0         0.0      1.0
1         1.0      0.0
2         1.0      0.0
3         0.0      1.0
4         1.0      0.0
...       ...      ...
8119      1.0      0.0
8120      1.0      0.0
8121      1.0      0.0
8122      0.0      1.0
8123      1.0      0.0

[8124 rows x 2 columns]

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X ,Y, test_size=0.3, random_state=1)

6848    0.0
2246    0.0
2095    0.0
4535    0.0
6865    0.0
       ...
7935    0.0
5192    0.0
3980    0.0
235     0.0
5157    0.0
Name: cap-shape_c, Length: 5686, dtype: float64