In [7]:
import pandas as pd

# Creazione DataFrame di esempio
df = pd.DataFrame({
    'città': ['Roma', 'Milano', 'Roma', 'Napoli', 'Milano'],
    'voto': ['A', 'B', 'A', 'C', 'B']
})

# Conversione singola colonna
df['città'] = df['città'].astype('category')

# Conversione di più colonne contemporaneamente
cols_to_fix = ['città', 'voto']
df[cols_to_fix] = df[cols_to_fix].astype('category')

In [8]:
df.head()

    città voto
0    Roma    A
1  Milano    B
2    Roma    A
3  Napoli    C
4  Milano    B

In [10]:
df2 = pd.DataFrame()
df2["città"]=df["città"]
df2["città codificata"] = df["città"].cat.codes

In [ ]:
df2.head()

   città codificata
0                 2
1                 0
2                 2
3                 1
4                 0